<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>

<%@page import="gdp18.waterlock.Utils" %>

<%@ taglib prefix="bbNG" uri="/bbNG"%>

<bbNG:genericPage ctxId="ctx" >

	<%
		String page_title = "Waterlock Authentication Settings";
	
		String providerID = request.getParameter("providerID");
		String sharedKey = request.getParameter("sharedKey");
		String expirySeconds = request.getParameter("expirySeconds");
		
		if (providerID != null){
			if(!providerID.trim().equals("") && Utils.isValidXML(providerID.trim())){
		        Utils.pluginSettings.setProviderID(providerID.trim());
		    }
		}
		
		if (sharedKey != null){
			if(!sharedKey.trim().equals("") && Utils.isValidXML(sharedKey.trim())){
		        Utils.pluginSettings.setSharedKey(sharedKey.trim());
		    }
		}

		if (expirySeconds != null){
			if (Utils.isInteger(expirySeconds)){
				int seconds = Integer.parseInt(expirySeconds);
				Utils.pluginSettings.setJWTExpirySeconds(seconds);
			}
		}
		
		providerID = Utils.pluginSettings.getProviderID();
		sharedKey = Utils.pluginSettings.getSharedKey();
		expirySeconds = String.valueOf(Utils.pluginSettings.getJWTExpirySeconds());
	%>
	<bbNG:pageHeader instructions="The settings for communication with Waterlock Authentication modules.">
		<bbNG:breadcrumbBar>
			<bbNG:breadcrumb><%= page_title %></bbNG:breadcrumb>
		</bbNG:breadcrumbBar>
		<bbNG:pageTitleBar ><%= page_title %></bbNG:pageTitleBar>
	</bbNG:pageHeader>
	
	<bbNG:form action="Config.jsp" method="post" onSubmit="return validateForm();">	
		<bbNG:dataCollection>
			<bbNG:step title="Settings">
				<bbNG:dataElement label="Provider ID" isRequired="true" labelFor="Provider ID">
					<bbNG:textElement name="providerID" value="<%= providerID %>" helpText="The name of this Blackboard instance"/>
				</bbNG:dataElement>
				<bbNG:dataElement label="Shared Key" isRequired="true" labelFor="Shared Key">
					<bbNG:textElement name="sharedKey" value="<%= sharedKey %>" helpText="The shared key to use for Single Sign On. The Waterlock module should use the same shared key. "/>
				</bbNG:dataElement>
				<bbNG:dataElement label="JWT expiry seconds" isRequired="true" labelFor="JWT Expiry Seconds">
					<bbNG:textElement name="expirySeconds" value="<%= expirySeconds %>" helpText="The number of seconds a JWT generated by this building block is valid for. "/>
				</bbNG:dataElement>
			</bbNG:step>
			<bbNG:stepSubmit/>
		</bbNG:dataCollection>
	</bbNG:form>
</bbNG:genericPage>
